version: 1.0.{build}
branches:
  only:
  - AppVeyorConfig
image: Visual Studio 2015

install:
- ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

before_build:
  - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
  #- ps: Vsix-TokenReplacement CopyAsHtml\CopyAsHtml\source.extension.cs 'Version = "([0-9\\.]+)"' 'Version = "{version}"'

build_script:
  - msbuild src/ProPowerTools.Open.sln /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

after_test:
  - ps: Vsix-PushArtifacts #| Vsix-PublishToGallery